name: API Tests with Newman
on:
  push:
    branches:
      - master
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Fix API URLs
      run: |
        sed -i 's/fakestoreapi\.com/dummyjson.com/g' "collections/E-Commerce API.postman_collection.json"

    - name: Run Postman Collection
      run: |
        newman run "collections/E-Commerce API.postman_collection.json" \
        -r cli,htmlextra \
        --reporter-htmlextra-export report.html \
        --timeout-request 10000

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: postman-report
        path: report.html
